### ISSUE TITLE
ClassNotFoundException: java.lang.UNIXProcess

### ISSUE THREAD

**Issue by j-cr** [borkdude/babashka#182] opened 2019-12-21 08:35 UTC
**version**
0.0.46-SNAPSHOT

**platform**
openjdk version "11.0.5" 2019-10-15

**problem**
```
Syntax error (ClassNotFoundException) compiling at (src/babashka/impl/classes.clj:113:16).
java.lang.UNIXProcess
Syntax error (ClassNotFoundException) compiling at (src/babashka/impl/classes.clj:113:16).
java.lang.UNIXProcess$ProcessPipeOutputStream
```

See the two lines: https://github.com/borkdude/babashka/blob/master/src/babashka/impl/classes.clj#L28

I don't think these 2 classes are [in the docs](https://docs.oracle.com/en/java/javase/13/docs/api/java.base/java/lang/package-summary.html), commenting these two lines out doesn't seem to affect anything.

**repro**

```
git clone https://github.com/borkdude/babashka.git
cd babashka
lein test
```

**Comment by borkdude** [comment] 2019-12-21 08:45
@j-cr These classes are needed to support interop for `ProcessBuilder` and `Process`. Currently Babashka is compiled with JDK8 (which was the only JDK available for GraalVM until recently). There is an issue for JDK 11 here: #120. I'm closing this as a duplicate of that issue.

**Closed by borkdude** 2019-12-21 08:45 UTC

**Comment by j-cr** [comment] 2019-12-21 08:46
Gotcha, sorry for not checking the issues more closely!
