### ISSUE TITLE
Vim-Fireplace error when evaluating in namespaced files.

### ISSUE THREAD

**Issue by JpOnline** [borkdude/babashka#633] opened 2020-11-06 18:06 UTC
bb Version 0.2.3
Vim 8.1
Vim-Fireplace 2.1

In a Debian Linux

I figured out the problem when trying to run [4bb](https://github.com/porkostomus/4bb), not even writing the .nrepl-port file as documented in [repl.md](https://github.com/borkdude/babashka/blob/master/doc/repl.md#nrepl) it works. I can run Clojure expressions using cpp in the [problems.clj](https://github.com/porkostomus/4bb/blob/master/problems.clj) file, but not in the [tests.clj](https://github.com/porkostomus/4bb/blob/master/tests.clj).

**Comment by borkdude** [comment] 2020-11-06 18:09
Do you have more information? What kind of problem is reported? What are the exact steps to reproduce? I'm not familiar with vim and fireplace. Try running the nREPL server with `BABASHKA_DEV=true bb --nrepl-server` and post the output here.

**Comment by borkdude** [comment] 2020-11-07 15:20
I'm suspecting this is not a bug with an nREPL server, but without more information this issue is not actionable. Closing for now. I will re-open if you provide more information.

**Closed by borkdude** 2020-11-07 15:20 UTC
