### ISSUE TITLE
version-clj fails when included via "use"

### ISSUE THREAD

**Issue by lread** [borkdude/babashka#565] opened 2020-09-04 22:26 UTC
**version**
v0.2.0

**platform**
macOS v10.15.6 
openjdk v11.0.8

**problem**
When including `version-clj.core` via `use` we get a `StackOverflowError`.

**repro**
From an empty directory so you don't accidentally pick up extra deps from some project, issue the following shell commands:
```
export BABASHKA_CLASSPATH=$(clojure -Spath -Sdeps '{:deps {version-clj {:mvn/version "0.1.2"}}}')
bb -e "(use 'version-clj.core) (version->seq \"1.0.0-SNAPSHOT\")" 
```

**actual behavior**
Ouput is:
```
----- Error --------------------------------------------------------------------
Type:     java.lang.StackOverflowError
Location: version_clj/split.clj:61:3

----- Context ------------------------------------------------------------------
57: ;; ## Split Points
58: 
59: (defn- split
60:   [v s]
61:   (if (fn? v)
      ^--- 
62:     (v s)
63:     (string/split s v)))
64: 
65: ;; ## Predefined Split Points
66: 

----- Locals -------------------------------------------------------------------
v: "1.0.0-SNAPSHOT"
s: #"\."

----- Stack trace --------------------------------------------------------------
version-clj.split/split                - version_clj/split.clj:59:8
version-clj.split/split                - version_clj/split.clj:63:5
version-clj.split/split                - version_clj/split.clj:59:8
version-clj.split/first-split-at-point - version_clj/split.clj:106:15
version-clj.split/first-split-at-point - version_clj/split.clj:102:8
version-clj.split                      - version_clj/split.clj:132:20
version-clj.core/version->seq          - version_clj/split.clj:7:6
version-clj.split                      - version_clj/split.clj:127:16
version-clj.core/version->seq          - version_clj/split.clj:7:6
user                                   - <expr>:1:25
```

**expected behavior**
If we employ `require` instead of `use`:
```
bb -e "(require '[version-clj.core :as ver]) (ver/version->seq \"1.0.0-SNAPSHOT\")"
```
We get an expected output:
```
[(1 0 0) ["snapshot"]]
```

**diagnosis**
In a Slack chat, borkdude guessed that:
> split is private, but bb currently doesn't honor private

**note to fixer**
Also from chat with borkdude on Slack:
> What I usually do for libraries like this is copy the tests to test-resources and add it to the lib tests script
> so they will be tested on CI
> like a smoke test

**Comment by borkdude** [comment] 2020-09-05 09:16
Repro:

/tmp/foo.clj
``` 
(ns foo (:require [clojure.string :as s]))

(defn split [s v]
  (s/split s v))
``` 

Execute `bb -cp /tmp -e "(use 'foo) (split 1 2)"`  and the stackoverflow will happen. I also found the cause: the `use` setting transitively works over all required namespaces, which is definitely a bug, but easy to fix.

**Comment by borkdude** [comment] 2020-09-06 20:01
Another repro:

``` 
$ bb '(ns foo (:use [clojure.string :as str])) (defn split [x y] (str/split x y))'
#'clojure.string/split
``` 

``` 
$ bb '(ns foo (:use [clojure.string :as str])) (defn split [x y] (str/split x y)) (split "foo" #"o")'
``` 

May have uncovered two bugs with `use`:

- Use will infect all transitively required namespaces, they are not only required, but also `use`d. This one was already mentioned in the previous comment.
- The above examples show that when defining a function with the same name as a `use` function, it will redefine that other function. And the redefinition is recursive (without `recur`), hence the stackoverflow.

**Comment by borkdude** [comment] 2020-09-06 21:31
The second problem has been addressed in https://github.com/borkdude/sci/issues/398.

**Comment by borkdude** [comment] 2020-09-06 21:41
And the first part now also has been addressed. Please try again with babashka master @lread!

**Comment by lread** [comment] 2020-09-07 18:56
Works over here with a locally built `bb` off master @borkdude, thanks!

```shell
mkdir testing123
cd testing123
export BABASHKA_CLASSPATH=$(clojure -Spath -Sdeps '{:deps {version-clj {:mvn/version "0.1.2"}}}')
../bb -e "(use 'version-clj.core) (version->seq \"1.0.0-SNAPSHOT\")"
```
Now gives expected output:
```Clojure
[(1 0 0) ["snapshot"]]
```

**Comment by borkdude** [comment] 2020-09-09 18:41
I think I'd be nice to copy the tests of version-clj into this repo and add them to lib-tests. I'll leave this issue open until we have done that.

**Comment by lread** [comment] 2020-09-09 18:49
@borkdude, I'll take care of adding the version-clj tests.

**Comment by borkdude** [comment] 2020-09-09 18:52
@lread Thanks! See `test-resources/lib_tests` and `script/run_lib_tests`

**Closed** 2020-09-09 21:03 UTC
Labels: bug
